### ISSUE TITLE
404

### ISSUE THREAD

**Issue by gewondjan** [byuitechops/create-homepage#22]
```
create-homepag… error                     message: Status Code 404 | GET | https://byui.instructure.com/api/v1/courses/16631/pages/550181 | {"message":"page not found"} stack: Error: Status Code 404 | GET | https://byui.instructure.com/api/v1/courses/16631/pages/550181 | {"message":"page not found"}
    at Request.request [as _callback] (C:\Users\jedimasterryan\repos\d2l-to-canvas-conversion-tool\node_modules\canvas-wrapper\canvas.js:104:70)
    at Request.self.callback (C:\Users\jedimasterryan\repos\d2l-to-canvas-conversion-tool\node_modules\request\request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\jedimasterryan\repos\d2l-to-canvas-conversion-tool\node_modules\request\request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\Users\jedimasterryan\repos\d2l-to-canvas-conversion-tool\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
```

**Comment by danverde** [comment]
Fixed in commit 87fc263174
